### ISSUE TITLE
SoilGrid file is not shared!

### ISSUE THREAD

**Issue by shahab271069** [SoilWatch/soil-erosion-watch#1]
Hey 

Thank you for your magnificent work. However, some datasets such as soil grids are not avialable!
Can you help me with this issue?

Best

**Comment by wouellette** [comment]
Hi @shahab271069,

You can access the soil grid layers with this syntax in the code editor:
`var <layer_name> = ee.Image("projects/soilgrids-isric/<layer_name>")`

For instance, to get the clay content layer: 
`var clay = ee.Image("projects/soilgrids-isric/clay_mean");`

I hope this helps!

Regards

**Comment by shahab271069** [comment]
Dear William

Thank you for your reply. I can not access dataset. Do you what is the problem?

Bets Wishes
Shahab

**Comment by wouellette** [comment]
Hi Shahab, 

It is not possible that you cannot access the collection because it is being accessed by the Soil Erosion Watch App, which means the dataset is public.
Check under this app link:
[https://code.earthengine.google.com/5ab4194419a2f5e3ee38e6ddbb414e86](https://code.earthengine.google.com/5ab4194419a2f5e3ee38e6ddbb414e86)

**Comment by wouellette** [comment]
Closing this issue. Please re-open if you happen to still have issues.

**Comment by shahab271069** [comment]
Sorry for late response.

I get access to dataset.

Thanks.
