### ISSUE TITLE
Soil Erosion Watch

### ISSUE THREAD

**Issue by francescatrevisan** [SoilWatch/soil-erosion-watch#6]
Hi William,

I am a PhD student from the University of Surrey and I would like to use your app as I am studying social dynamics related to environmental parametes. One of the parameters I am assessing is soil erosion, this is why I found your app super useful!

Through the app it is possible to perform analysis at monthly and annual scale however, when I run the analysis at monthly scale, the mangitude of change is at annual rate. Even if the analysis considers satellite data from a single month, is the magnitude going to be always at annual rate or could it be at monthly rate? 

Thanks for your help and contribution!

Francesca

**Comment by wouellette** [comment]
Hi Francesca,

The way the RUSLE equation is implemented is that it makes assumptions on annual vegetation cover dynamics, i.e. taking vegetation phenology into account.

Extracting RUSLE for a given month will mean you use data of that month only, including rainfall, satellites observations, and all other temporal inputs to the equation. In some cases, you main not have any satellite observations if too cloudy.

So even if theoretically extracting RUSLE on a monthly basis is possible, I wouldn't recommend it due to the reliance of the calculation on observational temporal data, which may be absent, or only partly available, making the estimation shaky in the best of cases, and impossible in the worst of cases (the loading of layers would just fail).

The fact that the data is expressed in t.ha-1.yr-1 is merely the extrapolation of the equation results for that given month, over a 1 year time-span. For instance, if you generate the data for the month of July in the temperate northern hemisphere, the rainfall is fairly low and vegetation cover fairly high, so you would get a relatively lower soil loss estimation than if you calculated it for the month of December. Theoretically, you could divide the value by 12, but since the distribution of soil loss across the year is not evenly distributed, I also would be careful doing that.

I use the global rainfall erosivity (factor R) derived from `Panagos, Panos, et al. "Global rainfall erosivity assessment based on high-temporal resolution rainfall records." Scientific reports 7.1 (2017): 1-12.` for the R factor, which is globally derived per annum.

If you would want to adequately model monthly timesteps, you would have to recalculate this R factor monthly (the C factor is already calculated monthly in this repository using temporal Sentinel-2 data when you select `1. 1 month`).

This [paper](https://www.tandfonline.com/doi/full/10.1080/17445647.2019.1585980) actually does this. If generating a monthly-timestep R factor would fall within the scope of applicability of your PhD, consider contributing to this repository with this monthly R factor!

I hope this helps.

Regards,

William
