### ISSUE TITLE
Include polygon for soil erosion watch

### ISSUE THREAD

**Issue by marcelocarvalhoalves** [SoilWatch/soil-erosion-watch#9]
Would it be possible to set up a polygon of interest to include the analysis of a smaller area by soil erosion watch without being a manually drawn polygon?

Thank you 

All the best,

Marcelo

**Comment by wouellette** [comment]
Hi Marcelo,

Unfortunately, since the Earth Engine App provided does not require authentication, it also cannot allow you to upload a polygon of interest. I suggest you copy the source code into a repository on your account, and add your own polygon in the interface that way by uploading it as a `FeatureCollection`. That would be the easiest way I reckon.

Regards,

William
